// One-time generator for the pre-refactor v1 header byte corpus (specs/003).
//
// Run manually against UNTOUCHED pre-refactor code, before the codec-version-
// strategies extraction lands, via:
//   cd packages/myenc_core && dart test/fixtures/generate_header_corpus.dart
//
// encodeHeader/decodeHeader are pure functions (no randomness), so the
// encoded bytes recorded here must stay byte-identical after the refactor.
// Do not re-run this after the refactor lands — fixtures_header_corpus_test.dart
// must verify these committed bytes against the NEW code, not bytes
// regenerated by it.
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:myenc_core/myenc_core.dart';

String _hex(Uint8List bytes) =>
    bytes.map((b) => b.toRadixString(16).padLeft(2, '0')).join();

Uint8List _bytes(int len, int seed) =>
    Uint8List.fromList(List.generate(len, (i) => (i + seed) % 256));

WrapEntry _wrap(WrapType type, int len, int seed) =>
    WrapEntry(type: type, bytes: _bytes(len, seed));

void main() {
  final cases = <String, FileHeader>{
    'no_wraps': FileHeader(
      version: FormatVersionRegistry.writeDefault.number,
      flags: 0,
      kdfId: FileHeader.kdfArgon2id,
      salt: _bytes(16, 0),
      opslimit: 2,
      memlimit: 65536,
      cipherId: FileHeader.cipherXchacha20Poly1305,
      chunkSize: FileHeader.defaultChunkSize,
      keyIdHint: _bytes(16, 16),
      wraps: const [],
      secretstreamHeader: _bytes(24, 100),
    ),
    'one_passphrase_wrap': FileHeader(
      version: FormatVersionRegistry.writeDefault.number,
      flags: 0,
      kdfId: FileHeader.kdfArgon2id,
      salt: _bytes(16, 1),
      opslimit: 3,
      memlimit: 131072,
      cipherId: FileHeader.cipherXchacha20Poly1305,
      chunkSize: FileHeader.defaultChunkSize,
      keyIdHint: _bytes(16, 17),
      wraps: [_wrap(WrapType.passphrase, 48, 200)],
      secretstreamHeader: _bytes(24, 101),
    ),
    'multiple_wraps': FileHeader(
      version: FormatVersionRegistry.writeDefault.number,
      flags: 0,
      kdfId: FileHeader.kdfArgon2id,
      salt: _bytes(16, 2),
      opslimit: 4,
      memlimit: 262144,
      cipherId: FileHeader.cipherXchacha20Poly1305,
      chunkSize: FileHeader.defaultChunkSize,
      keyIdHint: _bytes(16, 18),
      wraps: [
        _wrap(WrapType.passphrase, 48, 210),
        _wrap(WrapType.hardwareKey, 48, 220),
        _wrap(WrapType.recipient, 80, 230),
      ],
      secretstreamHeader: _bytes(24, 102),
    ),
    'encrypted_filename_present': FileHeader(
      version: FormatVersionRegistry.writeDefault.number,
      flags: 0x01,
      kdfId: FileHeader.kdfArgon2id,
      salt: _bytes(16, 3),
      opslimit: 2,
      memlimit: 65536,
      cipherId: FileHeader.cipherXchacha20Poly1305,
      chunkSize: FileHeader.defaultChunkSize,
      keyIdHint: _bytes(16, 19),
      wraps: [_wrap(WrapType.passphrase, 48, 240)],
      secretstreamHeader: _bytes(24, 103),
      encryptedFilename: _bytes(37, 250),
    ),
    'min_chunk_size_boundary': FileHeader(
      version: FormatVersionRegistry.writeDefault.number,
      flags: 0,
      kdfId: FileHeader.kdfArgon2id,
      salt: _bytes(16, 4),
      opslimit: FileHeader.minOpslimit,
      memlimit: FileHeader.minMemlimitKib,
      cipherId: FileHeader.cipherXchacha20Poly1305,
      chunkSize: FileHeader.minChunkSize,
      keyIdHint: _bytes(16, 20),
      wraps: [_wrap(WrapType.passphrase, 48, 5)],
      secretstreamHeader: _bytes(24, 104),
    ),
    'max_chunk_size_boundary': FileHeader(
      version: FormatVersionRegistry.writeDefault.number,
      flags: 0,
      kdfId: FileHeader.kdfArgon2id,
      salt: _bytes(16, 5),
      opslimit: FileHeader.maxOpslimit,
      memlimit: FileHeader.maxMemlimitKib,
      cipherId: FileHeader.cipherXchacha20Poly1305,
      chunkSize: FileHeader.maxChunkSize,
      keyIdHint: _bytes(16, 21),
      wraps: [_wrap(WrapType.passphrase, 48, 6)],
      secretstreamHeader: _bytes(24, 105),
    ),
  };

  final corpus = <String, dynamic>{};
  for (final entry in cases.entries) {
    final encoded = MyencCodec.encodeHeader(entry.value);
    corpus[entry.key] = {
      'encoded_hex': _hex(encoded),
      'encoded_length': encoded.length,
      'wrap_count': entry.value.wraps.length,
      'filename_encrypted': entry.value.filenameEncrypted,
      'chunk_size': entry.value.chunkSize,
    };
  }

  File(
    'test/fixtures/header_corpus.json',
  ).writeAsStringSync(const JsonEncoder.withIndent('  ').convert(corpus));

  // ignore: avoid_print
  print('header corpus written to test/fixtures/header_corpus.json');
}
