// One-time generator for the pre-refactor v1 compatibility corpus (specs/003).
//
// Run manually against UNTOUCHED pre-refactor code, before the codec-version-
// strategies extraction lands, via:
//   cd packages/myenc_adapters && flutter test test/fixtures/compat_v1/generate_fixtures.dart
//
// Writes raw plaintexts + .latch fixtures + manifest.json under this
// directory using the CURRENT (old) EnvelopeService/SodiumCryptoAdapter code
// path. Not part of the automated suite (no _test.dart suffix, no test()
// calls) — do not re-run this after the refactor lands, or it stops proving
// anything: compat_v1_test.dart must verify these committed bytes decrypt
// correctly under the NEW code, not bytes regenerated by the new code.
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:crypto/crypto.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:myenc_core/myenc_core.dart';
import 'package:sodium/sodium_sumo.dart';
import 'package:myenc_adapters/src/crypto/sodium_crypto_adapter.dart';

const _passphrase = 'compat-v1-fixture-passphrase';
const _wrongPassphrase = 'this-is-the-wrong-passphrase';
const _params = KdfParams(opslimit: 2, memlimit: 65536);

Future<List<int>> _collect(Stream<Uint8List> s) async {
  final out = <int>[];
  await for (final c in s) {
    out.addAll(c);
  }
  return out;
}

String _sha256Hex(List<int> bytes) => sha256.convert(bytes).toString();

Future<void> main() async {
  final sodium = await SodiumSumoInit.init();
  final adapter = SodiumCryptoAdapter(sodium);
  final envelope = EnvelopeService(adapter);
  final dir = Directory('test/fixtures/compat_v1');
  final rawDir = Directory('${dir.path}/raw')..createSync(recursive: true);
  final latchDir = Directory('${dir.path}/latch')..createSync(recursive: true);

  final cases = <String, Uint8List>{
    'empty': Uint8List(0),
    'one_byte': Uint8List.fromList([0x42]),
    'small': utf8.encode('the quick brown fox jumps over the lazy dog'),
    'multi_chunk': Uint8List.fromList(
      List.generate(70000, (i) => i % 256),
    ), // > 64KiB default chunk size
    'binary': Uint8List.fromList(
      List.generate(4096, (i) => (i * 31 + 7) % 256),
    ),
  };

  final manifest = <String, dynamic>{
    'passphrase': _passphrase,
    'wrong_passphrase': _wrongPassphrase,
    'kdf_params': {'opslimit': _params.opslimit, 'memlimit': _params.memlimit},
    'files': <String, dynamic>{},
  };

  for (final entry in cases.entries) {
    final name = entry.key;
    final raw = entry.value;
    File('${rawDir.path}/$name.bin').writeAsBytesSync(raw);

    final latch = Uint8List.fromList(
      await _collect(
        envelope.encrypt(
          plaintext: Stream.value(raw),
          passphrase: utf8.encode(_passphrase),
          params: _params,
          filename: '$name.bin',
        ),
      ),
    );
    File('${latchDir.path}/$name.latch').writeAsBytesSync(latch);

    manifest['files'][name] = {
      'raw_sha256': _sha256Hex(raw),
      'raw_length': raw.length,
      'latch_file': 'latch/$name.latch',
      'raw_file': 'raw/$name.bin',
    };
  }

  // Negative fixture 1: a valid file, opened with the wrong passphrase.
  // Reuse the 'small' case's ciphertext — must fail fast at the DEK wrap,
  // before any body bytes are touched.
  manifest['wrong_passphrase_fixture'] = 'latch/small.latch';

  // Negative fixture 2: a valid file with the last body byte flipped —
  // must fail at a chunk tag, never emitting partial plaintext.
  final smallLatch = File('${latchDir.path}/small.latch').readAsBytesSync();
  final tampered = Uint8List.fromList(smallLatch);
  tampered[tampered.length - 1] ^= 0x01;
  File('${latchDir.path}/tampered_body.latch').writeAsBytesSync(tampered);
  manifest['tampered_body_fixture'] = 'latch/tampered_body.latch';

  File(
    '${dir.path}/manifest.json',
  ).writeAsStringSync(const JsonEncoder.withIndent('  ').convert(manifest));

  // ignore: avoid_print
  print('compat_v1 fixtures written to ${dir.path}');
}
