import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:path/path.dart' as p;
import 'package:shared_preferences/shared_preferences.dart';
import '../../shared/theme/app_theme.dart';
import '../../shared/widgets/latch_button.dart';
import '../../core/app_crypto.dart';
import '../../core/crypto_stub.dart';
import '../../core/passphrase_policy.dart';

class EncryptPassphraseScreen extends StatefulWidget {
  final List<String> files;
  const EncryptPassphraseScreen({super.key, required this.files});

  @override
  State<EncryptPassphraseScreen> createState() =>
      _EncryptPassphraseScreenState();
}

class _EncryptPassphraseScreenState extends State<EncryptPassphraseScreen> {
  final _controller = TextEditingController();
  final _nameController = TextEditingController();
  bool _obscure = true;
  bool _saveForQuickUnlock = false;
  bool _canSave = false;
  PassphraseResult? _strength;
  int _selectedChip = 0;

  @override
  void initState() {
    super.initState();
    _controller.addListener(() {
      setState(() {
        _strength = _controller.text.isEmpty
            ? null
            : CryptoStub.evaluate(_controller.text);
      });
    });
    _checkAuth();
  }

  Future<void> _checkAuth() async {
    final svc = AppCrypto.passphraseStorage;
    if (svc == null) return;
    // Respect an explicit "the app stores nothing" choice from Settings.
    if (!await PassphrasePolicy.storageAllowed()) return;
    final ok = await svc.canAuthenticate;
    if (mounted) setState(() => _canSave = ok);
  }

  Future<void> _onChipSelected(int index) async {
    setState(() => _selectedChip = index);
    if (index == 1) {
      await _pickFromApp();
    }
  }

  Future<void> _pickFromApp() async {
    final svc = AppCrypto.passphraseStorage;
    if (svc == null || !mounted) return;
    final entries = await svc.list();
    if (entries.isEmpty) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text(
              'No saved passphrases yet. Save one on this screen first.',
            ),
          ),
        );
      }
      return;
    }
    if (!mounted) return;
    final label = await showModalBottomSheet<String>(
      context: context,
      builder: (ctx) => SafeArea(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Padding(
              padding: EdgeInsets.all(16),
              child: Text(
                'Pick a saved passphrase',
                style: TextStyle(fontWeight: FontWeight.w600, fontSize: 16),
              ),
            ),
            // Flexible + ListView: a long vault list scrolls inside the
            // sheet instead of overflowing it.
            Flexible(
              child: ListView(
                shrinkWrap: true,
                children: entries
                    .map(
                      (e) => ListTile(
                        leading: const Icon(Icons.vpn_key_outlined),
                        title: Text(
                          _displayLabel(e.label),
                          maxLines: 1,
                          overflow: TextOverflow.ellipsis,
                        ),
                        subtitle: Text('Saved ${_friendlyDate(e.createdAt)}'),
                        onTap: () => Navigator.pop(ctx, e.label),
                      ),
                    )
                    .toList(),
              ),
            ),
          ],
        ),
      ),
    );
    if (label == null || !mounted) return;
    String? passphrase;
    try {
      passphrase = await svc.loadWithAuth(label);
    } catch (e) {
      // A platform-level auth failure must be visible, not a silent no-op.
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Could not show the unlock prompt: $e')),
        );
      }
      return;
    }
    if (!mounted) return;
    if (passphrase != null) {
      _controller.text = passphrase;
    } else {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text(
            'Could not unlock the saved passphrase — authentication was cancelled or failed.',
          ),
        ),
      );
    }
  }

  /// Entries saved by older builds used the file path as the label — show
  /// just the basename for those.
  static String _displayLabel(String label) =>
      label.contains('/') ? p.basename(label) : label;

  static String _friendlyDate(DateTime dt) {
    final now = DateTime.now();
    final diff = now.difference(dt);
    if (diff.inDays == 0) return 'today';
    if (diff.inDays == 1) return 'yesterday';
    if (diff.inDays < 30) return '${diff.inDays}d ago';
    return '${dt.year}-${dt.month.toString().padLeft(2, '0')}-${dt.day.toString().padLeft(2, '0')}';
  }

  /// Neutral autogenerated vault name. Deliberately unrelated to the files
  /// being encrypted — a label like "taxes-2026.pdf" in the vault list would
  /// leak what the user encrypts.
  static String _autoName() {
    const months = [
      'Jan',
      'Feb',
      'Mar',
      'Apr',
      'May',
      'Jun',
      'Jul',
      'Aug',
      'Sep',
      'Oct',
      'Nov',
      'Dec',
    ];
    final now = DateTime.now();
    final hh = now.hour.toString().padLeft(2, '0');
    final mm = now.minute.toString().padLeft(2, '0');
    return 'Passphrase · ${now.day} ${months[now.month - 1]} $hh:$mm';
  }

  void _toggleSave() {
    setState(() {
      _saveForQuickUnlock = !_saveForQuickUnlock;
      if (_saveForQuickUnlock && _nameController.text.isEmpty) {
        _nameController.text = _autoName();
      }
    });
  }

  Future<void> _storeAndContinue() async {
    final svc = AppCrypto.passphraseStorage;
    String? keyIdHex;
    if (_saveForQuickUnlock && svc != null && _canSave) {
      final name = _nameController.text.trim();
      final label = name.isEmpty ? _autoName() : name;
      try {
        keyIdHex = await svc.store(label, _controller.text);
        // Saving implies the user wants quick unlock — turn it on so the
        // saved passphrase is actually offered at decrypt time.
        final prefs = await SharedPreferences.getInstance();
        await prefs.setBool('quick_unlock', true);
      } catch (e) {
        // Continue without quick unlock rather than silently doing nothing —
        // encryption itself must not be blocked by a vault failure.
        keyIdHex = null;
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text(
                'Could not save the passphrase — continuing without quick unlock.',
              ),
            ),
          );
        }
      }
    }
    if (mounted) {
      context.push(
        '/encrypt/options',
        extra: {
          'files': widget.files,
          'passphrase': _controller.text,
          'keyIdHex': keyIdHex,
        },
      );
    }
  }

  @override
  void dispose() {
    _controller.dispose();
    _nameController.dispose();
    super.dispose();
  }

  Color get _strengthColor {
    switch (_strength?.strength) {
      case PassphraseStrength.weak:
        return LatchColors.danger;
      case PassphraseStrength.fair:
        return LatchColors.caution;
      case PassphraseStrength.strong:
        return LatchColors.safe;
      case PassphraseStrength.veryStrong:
        return LatchColors.safe;
      default:
        return LatchColors.border;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        leading: BackButton(onPressed: () => context.pop()),
        title: const Text('Create a passphrase'),
      ),
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 16),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              _SourceChips(
                selected: _selectedChip,
                onSelected: _onChipSelected,
              ),
              const SizedBox(height: 20),
              if (_selectedChip == 2)
                AutofillGroup(
                  child: TextField(
                    controller: _controller,
                    obscureText: _obscure,
                    autofocus: true,
                    autofillHints: const [AutofillHints.newPassword],
                    decoration: InputDecoration(
                      hintText: 'Enter passphrase',
                      suffixIcon: TextButton(
                        onPressed: () => setState(() => _obscure = !_obscure),
                        child: Text(
                          _obscure ? 'show' : 'hide',
                          style: const TextStyle(color: LatchColors.subtle),
                        ),
                      ),
                    ),
                    style: const TextStyle(fontSize: 17, letterSpacing: 1.5),
                  ),
                )
              else
                TextField(
                  controller: _controller,
                  obscureText: _obscure,
                  autofocus: true,
                  decoration: InputDecoration(
                    hintText: 'Enter passphrase',
                    suffixIcon: TextButton(
                      onPressed: () => setState(() => _obscure = !_obscure),
                      child: Text(
                        _obscure ? 'show' : 'hide',
                        style: const TextStyle(color: LatchColors.subtle),
                      ),
                    ),
                  ),
                  style: const TextStyle(fontSize: 17, letterSpacing: 1.5),
                ),
              const SizedBox(height: 12),
              if (_strength != null) ...[
                _StrengthBar(score: _strength!.score, color: _strengthColor),
                const SizedBox(height: 8),
                Text(
                  _strength!.label,
                  style: TextStyle(fontSize: 13, color: _strengthColor),
                ),
              ],
              const SizedBox(height: 10),
              if (_canSave)
                Semantics(
                  button: true,
                  label: 'Save for quick unlock',
                  child: GestureDetector(
                    onTap: _toggleSave,
                    child: Container(
                      padding: const EdgeInsets.all(12),
                      decoration: BoxDecoration(
                        border: Border.all(
                          color: _saveForQuickUnlock
                              ? LatchColors.ink
                              : LatchColors.border,
                          width: _saveForQuickUnlock ? 2.5 : 1.5,
                        ),
                        borderRadius: BorderRadius.circular(12),
                      ),
                      child: Row(
                        children: [
                          Icon(
                            _saveForQuickUnlock
                                ? Icons.fingerprint
                                : Icons.fingerprint_outlined,
                            color: _saveForQuickUnlock
                                ? LatchColors.ink
                                : LatchColors.muted,
                            size: 20,
                          ),
                          const SizedBox(width: 10),
                          Expanded(
                            child: Text(
                              'Save for quick unlock',
                              style: Theme.of(context).textTheme.bodyMedium
                                  ?.copyWith(
                                    color: _saveForQuickUnlock
                                        ? LatchColors.ink
                                        : LatchColors.muted,
                                  ),
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
              if (_canSave && _saveForQuickUnlock) ...[
                const SizedBox(height: 10),
                TextField(
                  controller: _nameController,
                  decoration: const InputDecoration(
                    hintText: 'Name for this passphrase',
                    helperText: 'Just a label for your vault — pick anything.',
                  ),
                  style: const TextStyle(fontSize: 15),
                ),
              ],
              if (_canSave) const SizedBox(height: 10),
              Text(
                'A few random words beats hard-to-type symbols. Longer is stronger.',
                style: Theme.of(context).textTheme.bodySmall,
              ),
              const Spacer(),
              LatchPrimaryButton(
                label: 'Continue',
                onPressed: _controller.text.isNotEmpty
                    ? _storeAndContinue
                    : null,
              ),
              const SizedBox(height: 8),
            ],
          ),
        ),
      ),
    );
  }
}

class _SourceChips extends StatelessWidget {
  final int selected;
  final ValueChanged<int> onSelected;
  static const _labels = ['Type it', 'From app', 'Password mgr'];

  const _SourceChips({required this.selected, required this.onSelected});

  @override
  Widget build(BuildContext context) {
    return Wrap(
      spacing: 8,
      children: List.generate(_labels.length, (i) {
        final active = i == selected;
        return Semantics(
          button: true,
          label: _labels[i],
          child: GestureDetector(
            onTap: () => onSelected(i),
            child: Container(
              padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 14),
              decoration: BoxDecoration(
                color: active ? LatchColors.ink : Colors.transparent,
                border: Border.all(
                  color: active ? LatchColors.ink : LatchColors.border,
                  width: 2,
                ),
                borderRadius: BorderRadius.circular(20),
              ),
              child: Text(
                _labels[i],
                style: TextStyle(
                  fontSize: 13,
                  color: active ? Colors.white : LatchColors.muted,
                  fontWeight: FontWeight.w500,
                ),
              ),
            ),
          ),
        );
      }),
    );
  }
}

class _StrengthBar extends StatelessWidget {
  final double score;
  final Color color;

  const _StrengthBar({required this.score, required this.color});

  @override
  Widget build(BuildContext context) {
    return Row(
      children: List.generate(4, (i) {
        final filled = score > i * 0.25;
        return Expanded(
          child: Container(
            margin: EdgeInsets.only(right: i < 3 ? 4 : 0),
            height: 7,
            decoration: BoxDecoration(
              color: filled ? color : LatchColors.border,
              borderRadius: BorderRadius.circular(4),
            ),
          ),
        );
      }),
    );
  }
}
