import 'dart:typed_data';
import 'package:test/test.dart';
import 'package:myenc_core/myenc_core.dart';

/// Format v1 FREEZE tests (docs/FORMAT.md).
///
/// The expected header hex below was generated INDEPENDENTLY of MyencCodec
/// (a Python script expressing the layout table in docs/FORMAT.md §2).
/// If any of these tests fail, the wire format changed — that is forbidden
/// for v1. Bump the version byte instead.
///
/// The complementary end-to-end freeze (real Argon2id + secretstream bytes)
/// lives in packages/myenc_adapters/test/golden_vectors_test.dart against
/// the independently produced golden_v1.latch fixture.

/// Canonical v1 header: flags=0x01, salt 00..0f, opslimit 3, memlimit 65536,
/// chunk 65536, key-id 10..1f, passphrase wrap (72×AA), hardware wrap
/// (72×BB), enc-filename (45×CC), ss-header 20..37. Total 277 bytes.
const _frozenHeaderHex =
    '4c415443480101010010000102030405060708090a0b0c0d0e0f000000030001'
    '00000100010000101112131415161718191a1b1c1d1e1f02010048aaaaaaaaaa'
    'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
    'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
    'aaaaaa020048bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb'
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb'
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbb002dcccccccccccccccccccccccccccccccc'
    'cccccccccccccccccccccccccccccccccccccccccccccccccccccccccc202122'
    '232425262728292a2b2c2d2e2f3031323334353637';

Uint8List _hex(String s) {
  final out = Uint8List(s.length ~/ 2);
  for (var i = 0; i < out.length; i++) {
    out[i] = int.parse(s.substring(i * 2, i * 2 + 2), radix: 16);
  }
  return out;
}

FileHeader _canonicalHeader() => FileHeader(
  version: 1,
  flags: 0x01,
  kdfId: FileHeader.kdfArgon2id,
  salt: Uint8List.fromList(List.generate(16, (i) => i)),
  opslimit: 3,
  memlimit: 65536,
  cipherId: FileHeader.cipherXchacha20Poly1305,
  chunkSize: 65536,
  keyIdHint: Uint8List.fromList(List.generate(16, (i) => 0x10 + i)),
  wraps: [
    WrapEntry(
      type: WrapType.passphrase,
      bytes: Uint8List(72)..fillRange(0, 72, 0xAA),
    ),
    WrapEntry(
      type: WrapType.hardwareKey,
      bytes: Uint8List(72)..fillRange(0, 72, 0xBB),
    ),
  ],
  secretstreamHeader: Uint8List.fromList(List.generate(24, (i) => 0x20 + i)),
  encryptedFilename: Uint8List(45)..fillRange(0, 45, 0xCC),
);

void main() {
  group('format v1 freeze — frozen constants', () {
    test('structural constants may never change for v1', () {
      expect(FileHeader.supportedVersion, 1);
      expect(FileHeader.kdfArgon2id, 0x01);
      expect(FileHeader.cipherXchacha20Poly1305, 0x01);
      expect(FileHeader.secretstreamHeaderLength, 24);
      expect(FileHeader.secretstreamOverhead, 17);
      expect(FileHeader.knownFlagsMask, 0x01);
      expect(FileHeader.defaultChunkSize, 65536);
    });

    test('wrap type codes are frozen', () {
      expect(WrapType.passphrase.code, 0x01);
      expect(WrapType.hardwareKey.code, 0x02);
      expect(WrapType.recipient.code, 0x03);
    });

    test('decode-time bounds are frozen', () {
      expect(FileHeader.minChunkSize, 64);
      expect(FileHeader.maxChunkSize, 16 * 1024 * 1024);
      expect(FileHeader.minOpslimit, 1);
      expect(FileHeader.maxOpslimit, 64);
      expect(FileHeader.minMemlimitKib, 8);
      expect(FileHeader.maxMemlimitKib, 1024 * 1024);
    });

    test('encrypt-time security floor is frozen', () {
      expect(KdfParams.minOpslimit, 2);
      expect(KdfParams.minMemlimitKib, 65536);
    });
  });

  group('format v1 freeze — wire layout', () {
    test('encodeHeader produces the independently generated byte layout', () {
      final encoded = MyencCodec.encodeHeader(_canonicalHeader());
      expect(encoded, equals(_hex(_frozenHeaderHex)));
    });

    test('decodeHeader parses the frozen bytes back field-for-field', () {
      final frozen = _hex(_frozenHeaderHex);
      final (hdr, consumed) = MyencCodec.decodeHeader(frozen);

      expect(consumed, frozen.length);
      expect(hdr.version, 1);
      expect(hdr.flags, 0x01);
      expect(hdr.kdfId, FileHeader.kdfArgon2id);
      expect(hdr.salt, List.generate(16, (i) => i));
      expect(hdr.opslimit, 3);
      expect(hdr.memlimit, 65536);
      expect(hdr.cipherId, FileHeader.cipherXchacha20Poly1305);
      expect(hdr.chunkSize, 65536);
      expect(hdr.keyIdHint, List.generate(16, (i) => 0x10 + i));
      expect(hdr.wraps, hasLength(2));
      expect(hdr.wraps[0].type, WrapType.passphrase);
      expect(hdr.wraps[0].bytes, everyElement(0xAA));
      expect(hdr.wraps[1].type, WrapType.hardwareKey);
      expect(hdr.wraps[1].bytes, everyElement(0xBB));
      expect(hdr.encryptedFilename, isNotNull);
      expect(hdr.encryptedFilename, hasLength(45));
      expect(hdr.encryptedFilename, everyElement(0xCC));
      expect(hdr.secretstreamHeader, List.generate(24, (i) => 0x20 + i));
    });

    test('fixed prefix is exactly 56 bytes: wrap count sits at offset 55', () {
      final frozen = _hex(_frozenHeaderHex);
      expect(frozen[55], 2); // wrap count of the canonical header
    });
  });

  group('format v1 freeze — versioning policy', () {
    test(
      'any version the table does not know is rejected with VersionTooNewError',
      () {
        final bytes = _hex(_frozenHeaderHex);
        // The registry's first unknown version, not a literal: the guard pins
        // the fail-closed rule itself, so it can never go stale at a bump.
        bytes[5] = FormatVersionRegistry.firstUnknown;
        expect(
          () => MyencCodec.decodeHeader(bytes),
          throwsA(isA<VersionTooNewError>()),
        );
      },
    );

    test('every reserved flag bit is rejected', () {
      for (var bit = 1; bit < 8; bit++) {
        final bytes = _hex(_frozenHeaderHex);
        bytes[6] = bytes[6] | (1 << bit);
        expect(
          () => MyencCodec.decodeHeader(bytes),
          throwsA(isA<CorruptedFileError>()),
          reason: 'reserved flag bit $bit must be rejected',
        );
      }
    });

    test('wrap type codes above recipient are rejected', () {
      final bytes = _hex(_frozenHeaderHex);
      bytes[56] = 0x04; // first wrap's type byte
      expect(
        () => MyencCodec.decodeHeader(bytes),
        throwsA(isA<CorruptedFileError>()),
      );
    });
  });
}
